from __future__ import annotations

from loadtest.metrics import TableSyncStats


class PipelineRun:
    def __init__(self, cfg, timeout_s: float, poll_s: float): ...

    def start(self) -> None: ...

    def wait_until_synced(self, expected_rows: dict[str, int]) -> list[TableSyncStats]: ...

    def stop(self) -> None: ...

    def reset_target(self) -> None: ...
